### ISSUE TITLE
Support 1.16.5

### ISSUE THREAD

**Issue by matthewfcarlson** [3arthqu4ke/HeadlessForge#7]
Looking at modifying this into a sort of automation system by combining it with baritone and an orchestra framework (going for a bot hive mind type thing). As someone who is probably way more experience with this, what all is required to update this to 1.16.5, I know there were some big API changes in 1.12 -> 1.13 but I've been out of the forge community for a year or so and didn't do much graphical work.

**Comment by 3arthqu4ke** [comment]
Yes, since 1.16.5 seems to be the goto-version for many servers now I'm planning on doing it. Though, when working with Versions from 1.14 onward I would prefer Fabric. Do you need Forge specifically?

**Comment by matthewfcarlson** [comment]
Nope- I just am not as familiar with it. It was sort of the new fangled thing. Just because I'm curious- what does fabric offer?

**Comment by 3arthqu4ke** [comment]
For me it mainly comes down to one thing:
The Fabric Loader alone is much more light-weight than Forge. All the Fabric Loader does is give you a way to apply Patches to Vanilla Minecraft. Forge, however, comes with many Hooks and Events pre-applied, all of which I never use. If I wanted those I could use the [Fabric-API](https://github.com/FabricMC/fabric) which offers some standardized Hooks.

Depending on how easy it is to port this to 1.16.5 I might do both, we'll see.

**Comment by 3arthqu4ke** [comment]
Sorry this is coming almost a year later... but you might wanna check out https://github.com/3arthqu4ke/HeadlessMc
